parameters:
  - name: branch # folder containing the package.json file
    type: string
  - name: password # folder containing the package.json file
    type: string


stages:
  - stage: build
    jobs:
      - job: build
        pool:
          vmimage: ubuntu-latest # Needed for npm
        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
          # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
          - uses: actions/checkout@v3

          # Runs a single command using the runners shell
          - name: Run a one-line script
            run: echo Hello, world! from ${{ parameters.branch }}
